# Site settings
title: "Sana"
email: "questions@sanamobile.org"
description: > # this means to ignore newlines until "baseurl:"
  Sana platform user and technical documentation.
baseurl: "/sana.mobile" # the subpath of your site, e.g. /blog/
url: "http://sanamobile.github.io" # the base hostname & protocol for your site
# twitter_username: ""
github_username:  "sanamobile"

# Build settings
markdown: kramdown
